[tool.pylint]
max-line-length=100
disable=[
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "duplicate-code",
    ]
good-names="p"

[tool.mypy]
ignore_missing_imports = true
