[tool.pylint]
max-line-length=100
disable=[
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "duplicate-code",
    ]
good-names="p"

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.isort]
line_length = 100
